export const fetchBlogType = {
  STARTED: "FETCH_BLOG_STARTED",
  SUCCESS: "FETCH_BLOG_SUCCESS",
  ESUCCESS: "EDIT_BLOG_SUCCESS",
  DSUCCESS: "DELETE_BLOG_SUCCESS",
  FAILURE: "FETCH_BLOG_FAILURE",
};
